FROM maven:3.5.0-jdk-8-alpine as builder
COPY ./P12-order /app/P12-order
WORKDIR /app/P12-order
RUN mvn clean install -DskipTests

FROM openjdk:8u131-jre-alpine
COPY --from=builder /app/P12-order/target/order-0.0.1-SNAPSHOT.jar /app/order-0.0.1-SNAPSHOT.jar
WORKDIR /app
CMD java -jar order-0.0.1-SNAPSHOT.jar