FROM maven:3.5.0-jdk-8-alpine
COPY ./P12-configuration /usr/P12-configuration
WORKDIR /usr/P12-configuration
RUN mvn clean install -DskipTests

FROM openjdk:8u131-jre-alpine
COPY ./P12-configuration/target/config-0.0.1-SNAPSHOT.jar /usr/config-0.0.1-SNAPSHOT.jar
WORKDIR /usr
CMD java -jar config-0.0.1-SNAPSHOT.jar