FROM maven:3.5.0-jdk-8-alpine as builder
COPY ./P12-batch /app/P12-batch
WORKDIR /app/P12-batch
RUN mvn clean install -DskipTests

FROM openjdk:8u131-jre-alpine
COPY --from=builder /app/P12-batch/target/batch*.jar /app/batch.jar
WORKDIR /app
CMD java -jar batch.jar