FROM maven:3.5.0-jdk-8-alpine
COPY ./P12-stock /usr/P12-stock
WORKDIR /usr/P12-stock
RUN mvn clean install -DskipTests

FROM openjdk:8u131-jre-alpine
COPY ./P12-stock/target/stock-0.0.1-SNAPSHOT.jar /usr/stock-0.0.1-SNAPSHOT.jar
WORKDIR /usr
CMD java -jar stock-0.0.1-SNAPSHOT.jar