FROM node:12.2.0 as build

COPY ./P12-UI /app/P12-UI
WORKDIR /app/P12-UI

RUN npm install
RUN npm run build

FROM nginx:1.16.0-alpine
COPY --from=build /app/P12-UI/dist/P12-UI /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]