FROM maven:3.5.0-jdk-8-alpine as builder
COPY ./P12-stock /app/P12-stock
WORKDIR /app/P12-stock
RUN mvn clean install -DskipTests

FROM openjdk:8u131-jre-alpine
COPY --from=builder /app/P12-stock/target/stock*.jar /app/stock.jar
WORKDIR /app
CMD java -jar stock.jar