FROM maven:3.5.0-jdk-8-alpine
COPY ./P12-api-gateway /usr/P12-api-gateway
WORKDIR /usr/P12-api-gateway
RUN mvn clean install -DskipTests

FROM openjdk:8u131-jre-alpine
COPY ./P12-api-gateway/target/api-gateway-0.0.1-SNAPSHOT.jar /usr/api-gateway-0.0.1-SNAPSHOT.jar
WORKDIR /usr
CMD java -jar api-gateway-0.0.1-SNAPSHOT.jar