FROM maven:3.5.0-jdk-8-alpine as builder
COPY ./P12-instance-register /app/P12-instance-register
WORKDIR /app/P12-instance-register
RUN mvn clean install -DskipTests

FROM openjdk:8u131-jre-alpine
COPY --from=builder /app/P12-instance-register/target/register*.jar /app/register.jar
WORKDIR /app
CMD java -jar register.jar