FROM maven:3.5.0-jdk-8-alpine
COPY ./P12-account /usr/P12-account
WORKDIR /usr/P12-account
RUN mvn clean install -DskipTests

FROM openjdk:8u131-jre-alpine
COPY ./P12-account/target/account-0.0.1-SNAPSHOT.jar /usr/account-0.0.1-SNAPSHOT.jar
WORKDIR /usr
CMD java -jar account-0.0.1-SNAPSHOT.jar