FROM maven:3.5.0-jdk-8-alpine as builder
COPY ./P12-api-gateway /app/P12-api-gateway
WORKDIR /app/P12-api-gateway
RUN mvn clean install -DskipTests

FROM openjdk:8u131-jre-alpine
COPY --from=builder /app/P12-api-gateway/target/api-gateway*.jar /app/api-gateway.jar
WORKDIR /app
CMD java -jar api-gateway.jar