FROM maven:3.5.0-jdk-8-alpine
COPY ./P12-register /usr/P12-register
WORKDIR /usr/P12-register
RUN mvn clean install -DskipTests

FROM openjdk:8u131-jre-alpine
COPY ./P12-register/target/register-0.0.1-SNAPSHOT.jar /usr/register-0.0.1-SNAPSHOT.jar
WORKDIR /usr
CMD java -jar register-0.0.1-SNAPSHOT.jar