FROM maven:3.5.0-jdk-8-alpine
COPY ./P12-order /usr/P12-order
WORKDIR /usr/P12-order
RUN mvn clean install -DskipTests

FROM openjdk:8u131-jre-alpine
COPY ./P12-order/target/order-0.0.1-SNAPSHOT.jar /usr/order-0.0.1-SNAPSHOT.jar
WORKDIR /usr
CMD java -jar order-0.0.1-SNAPSHOT.jar