FROM maven:3.5.0-jdk-8-alpine as builder
COPY ./P12-api-gateway /app/P12-api-gateway
WORKDIR /app/P12-api-gateway
RUN mvn clean install -DskipTests

FROM openjdk:8u131-jre-alpine
COPY --form=builder /app/P12-api-gateway/target/api-gateway-0.0.1-SNAPSHOT.jar /app/api-gateway-0.0.1-SNAPSHOT.jar
WORKDIR /app
CMD java -jar api-gateway-0.0.1-SNAPSHOT.jar