FROM maven:3.5.0-jdk-8-alpine as builder
COPY ./P12-configuration /app/P12-configuration
WORKDIR /app/P12-configuration
RUN mvn clean install -DskipTests

FROM openjdk:8u131-jre-alpine
COPY --from=builder /app/P12-configuration/target/configuration*.jar /app/configuration.jar
WORKDIR /app
CMD java -jar configuration.jar